import React from "react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-gray-200 h-screen w-screen"}>
        {children}
      </body>
    </html>
  );
}
